### ISSUE TITLE
rt-fs does not work with the new CLI configuration

### ISSUE THREAD

**Issue by adim1** [jfrog/jfrog-cli-plugins#43]
Plugin name: rt-fs

The plugin does not recognize the new server configuration format.

Steps to reproduce:
1. Install the latest JFrog CLI version (1.46.4)
2. Configure Artifactory server (jfrog config add)
3. Install 'rt-fs' plugin
4. Run the command ls command, for example: _jfrog rt-fs ls generic-local_

**Expected behavior**
returning the files in the repository

Observed behavior
[Error] Server ID 'art-server-test' does not exist.
exit status 1

**Versions**
- CLI Plugin version: 1.46.4
- CLI Plugin operating system: 1.1.0
- Artifactory Version: 7.x

**Comment by yahavi** [comment]
Thanks for reporting this issue!

The root cause - 
We recently released JFrog CLI with a new configuration (v5). The rt-fs plugin worked with the old configuration (v4).

To fix the issue we upgraded the JFrog CLI core version to the latest.

`rt-fs` 1.1.1 is released. This version includes the fix. To upgrade, reinstall the plugin:
```sh
jfrog plugin uninstall rt-fs
jfrog plugin install rt-fs
```
